a = 4
try:
    pass
except a:
    pass

#*ERROR* 10.py:4: unknown or unsupported exception type
