try:
    pass
finally:
    pass

#*ERROR* 9.py:1: 'try..finally' is not supported
